/* =====================================================================
   Winex – sets, gebieden en demowijnen
   Pas hier de setcatalogus aan. Matchregels per vak (m):
     regio  – gebiedscode (bijv. 'bordeaux')
     app    – lijst appellations
     grape  – hoofddruif
     land   – land
     style  – 'stil' | 'mousserend' | 'zoet' | 'versterkt'
     color  – 'rood' | 'wit' | 'rosé'
     tag    – kenmerk (bijv. 'crianza', 'crémant')
     key    – exacte wijn (maker|naam, kleine letters)
   Alle opgegeven velden moeten kloppen. d = moeilijkheid (1 supermarkt, 2 wijnwinkel, 3 specialist).
   ===================================================================== */

const LANDS = ['Frankrijk','Italië','Spanje','Portugal','Duitsland','Oostenrijk','Nederland','Verenigd Koninkrijk','Zuid-Afrika','Chili','Argentinië','Verenigde Staten','Australië','Nieuw-Zeeland'];

/* Kleurpaletten en motieven voor de reisposters */
const AREAS = {
  bordeaux:{naam:'Bordeaux',land:'Frankrijk',motifs:['chateau','village'],c:{sky:'#EED3AC',sun:'#F09A3E',far:'#93607A',near:'#5A3550',dark:'#2E1A2A',m:'#F7EAD6'},art:{landmark:'chateau',water:'river',flora:'poplar'}},
  bourgogne:{naam:'Bourgogne',land:'Frankrijk',motifs:['church','village'],c:{sky:'#F3DDAA',sun:'#E4693A',far:'#B0734A',near:'#6B7A3E',dark:'#33401E',m:'#FAF0DA'},art:{landmark:'church',flora:'poplar'}},
  beaujolais:{naam:'Beaujolais',land:'Frankrijk',motifs:['village','church'],c:{sky:'#F2D6C9',sun:'#E8784A',far:'#B4687A',near:'#6E8B4E',dark:'#3A2A3E',m:'#FBEFE6'},art:{landmark:'village',flora:'poplar'}},
  jura:{naam:'Jura',land:'Frankrijk',motifs:['windmill','pines'],c:{sky:'#D3E4E1',sun:'#F2C462',far:'#7C9C95',near:'#47695A',dark:'#213A31',m:'#F5F0E2'},art:{landmark:'church',mount:'alps',flora:'pines'}},
  rhone:{naam:'Rhône',land:'Frankrijk',motifs:['chateau','cypress'],c:{sky:'#F6D9A0',sun:'#E46B2E',far:'#B57B57',near:'#7F7A3C',dark:'#3C3220',m:'#F8EBD3'},art:{landmark:'papal',water:'river',flora:'cypress',terraces:true}},
  loire:{naam:'Loire',land:'Frankrijk',motifs:['chateau','village'],c:{sky:'#D7E3EC',sun:'#F3C26B',far:'#8FA7B8',near:'#5E8156',dark:'#2B3C35',m:'#F5F1E8'},art:{landmark:'chateau',water:'river',flora:'poplar'}},
  champagne:{naam:'Champagne',land:'Frankrijk',motifs:['church','village'],c:{sky:'#EFE7D2',sun:'#E9B949',far:'#A6A07A',near:'#6F7F45',dark:'#2F3524',m:'#FFFDF5'},art:{landmark:'cathedral',flora:'poplar'}},
  elzas:{naam:'Elzas',land:'Frankrijk',motifs:['church','village'],c:{sky:'#E4E6D2',sun:'#EBB54A',far:'#8FA27E',near:'#5C7A45',dark:'#2C3A26',m:'#FBF6EA'},art:{landmark:'timber',mount:'alps',flora:'pines'}},
  languedoc:{naam:'Languedoc',land:'Frankrijk',motifs:['cypress','chateau'],c:{sky:'#F6D59C',sun:'#E5622F',far:'#BE8455',near:'#857A3E',dark:'#3E2F1E',m:'#FAEBD2'},art:{landmark:'walled',water:'sea',flora:'cypress'}},
  provence:{naam:'Provence',land:'Frankrijk',motifs:['farmhouse','cypress'],c:{sky:'#F3D7D0',sun:'#EE9A5C',far:'#B58FB0',near:'#8C9C5A',dark:'#3D3242',m:'#FFF6EE'},art:{landmark:'farmhouse',water:'sea',flora:'cypress',lavender:true}},
  piemonte:{naam:'Piemonte',land:'Italië',motifs:['mountains','village'],c:{sky:'#E6DCCB',sun:'#E07B45',far:'#9E8DA6',near:'#7D8650',dark:'#3A2D2E',m:'#FFFFFF'},art:{landmark:'castle',mount:'alps',flora:'poplar'}},
  veneto:{naam:'Veneto',land:'Italië',motifs:['church','cypress'],c:{sky:'#E2E3D8',sun:'#E9A64C',far:'#9AA493',near:'#6E8650',dark:'#2E3428',m:'#FBF7EC'},art:{landmark:'campanile',water:'lake',flora:'cypress'}},
  sicilie:{naam:'Sicilië',land:'Italië',motifs:['mountains','farmhouse'],c:{sky:'#F5C98B',sun:'#E0482E',far:'#B5764E',near:'#8A8A44',dark:'#41281C',m:'#FAEAD0'},art:{landmark:'church',mount:'volcano',water:'sea',flora:'cypress'}},
  toscane:{naam:'Toscane',land:'Italië',motifs:['cypress','farmhouse'],c:{sky:'#F7CD8E',sun:'#E05A38',far:'#C98F55',near:'#86924A',dark:'#3A4522',m:'#FBEBCF'},art:{landmark:'farmhouse',flora:'cypress'}},
  rioja:{naam:'Rioja',land:'Spanje',motifs:['mesa','village'],c:{sky:'#F5BE73',sun:'#FDE6A8',far:'#BC6A40',near:'#84402C',dark:'#47201A',m:'#F8E4C4'},art:{landmark:'bodega',mount:'mesa',flora:'poplar'}},
  'nieuw-zeeland':{naam:'Nieuw-Zeeland',land:'Nieuw-Zeeland',motifs:['mountains','pines'],c:{sky:'#B4D0E4',sun:'#FFF0C2',far:'#6A89A8',near:'#77A35C',dark:'#2F5130',m:'#FFFFFF'},art:{landmark:'farmhouse',mount:'alps',water:'lake',flora:'pines'}}
};
/* Terugval per land voor gebieden zonder eigen palet */
const LANDPAL = {
  'Frankrijk':{motifs:['village','church'],c:{sky:'#E9DCC0',sun:'#E58A45',far:'#9C7A8E',near:'#5F6E44',dark:'#2E2A26',m:'#FAF3E6'},art:{landmark:'church',flora:'poplar'}},
  'Italië':{motifs:['cypress','village'],c:{sky:'#F4D49A',sun:'#D9603A',far:'#B98557',near:'#7D8A44',dark:'#3A3A22',m:'#FBEED6'},art:{landmark:'campanile',flora:'cypress'}},
  'Spanje':{motifs:['mesa','village'],c:{sky:'#F3C27E',sun:'#FBE1A0',far:'#C27546',near:'#8C4A2E',dark:'#47231A',m:'#F8E6C8'},art:{landmark:'bodega',mount:'mesa',flora:'poplar'}},
  'Portugal':{motifs:['village','cypress'],c:{sky:'#F1D7A8',sun:'#E57A3C',far:'#A65E4E',near:'#6F7A3A',dark:'#352620',m:'#F7EADA'},art:{landmark:'farmhouse',water:'river',flora:'cypress',terraces:true}},
  'Duitsland':{motifs:['church','pines'],c:{sky:'#D9E2D3',sun:'#EFC25C',far:'#8C9C7E',near:'#4F6B45',dark:'#26332A',m:'#F6F2E6'},art:{landmark:'castle',water:'river',flora:'pines',terraces:true}},
  'Oostenrijk':{motifs:['mountains','church'],c:{sky:'#D5E3E8',sun:'#F2D27A',far:'#7F98A3',near:'#5E8352',dark:'#28392F',m:'#FFFFFF'},art:{landmark:'abbey',water:'river',mount:'alps',flora:'pines'}},
  'Nederland':{motifs:['windmill','village'],c:{sky:'#D8E4EE',sun:'#F0B54E',far:'#8DA3B5',near:'#5E8A4E',dark:'#2A3A3A',m:'#FAF7EE'},art:{landmark:'windmill',water:'lake',flora:'poplar'}},
  'Verenigd Koninkrijk':{motifs:['church','village'],c:{sky:'#DCE3E3',sun:'#EDC46A',far:'#93A1A0',near:'#5D7D51',dark:'#2B3530',m:'#FAF8F0'},art:{landmark:'church',flora:'poplar'}},
  'Zuid-Afrika':{motifs:['mesa','farmhouse'],c:{sky:'#F2CFA0',sun:'#E86A3A',far:'#A87A62',near:'#6A7E46',dark:'#2E2C22',m:'#FAF0E0'},art:{landmark:'gable',mount:'table',flora:'gum'}},
  'Chili':{motifs:['mountains','farmhouse'],c:{sky:'#E7D2B6',sun:'#E5733F',far:'#8E8AA6',near:'#7C8A4A',dark:'#30302A',m:'#FFFFFF'},art:{landmark:'farmhouse',mount:'andes',flora:'poplar'}},
  'Argentinië':{motifs:['mountains','village'],c:{sky:'#EAD7C0',sun:'#E77B45',far:'#9B85A0',near:'#8A7E48',dark:'#3A2C2A',m:'#FFFFFF'},art:{landmark:'bodega',mount:'andes',flora:'poplar'}},
  'Verenigde Staten':{motifs:['farmhouse','pines'],c:{sky:'#F3D3A4',sun:'#EA7A3E',far:'#B98A6A',near:'#7E8A48',dark:'#33301F',m:'#FAF0DE'},art:{landmark:'barn',flora:'redwood'}},
  'Australië':{motifs:['mesa','farmhouse'],c:{sky:'#F4C48A',sun:'#E4572E',far:'#C2704A',near:'#8E7E44',dark:'#40261C',m:'#FAEAD2'},art:{landmark:'farmhouse',flora:'gum'}},
  'Nieuw-Zeeland':{motifs:['mountains','pines'],c:{sky:'#B4D0E4',sun:'#FFF0C2',far:'#6A89A8',near:'#77A35C',dark:'#2F5130',m:'#FFFFFF'},art:{landmark:'farmhouse',mount:'alps',water:'lake',flora:'pines'}}
};

/* ---------- Sets ----------
   part 1 = regio (kaart zit hier fysiek), part 2 = verzamellijst (afdruk)
   unlock = zichtbaar zodra die set voltooid is; secret = zichtbaar zodra je eerste passende wijn binnen is
   always = altijd zichtbaar (verzamellijsten zonder always verschijnen zodra er één vak gevuld is) */
const S=(l,d,m)=>({l,d,m});
const SETS = [
  {id:'bordeaux-1',name:'Bordeaux I',part:1,land:'Frankrijk',area:'bordeaux',slots:[
    S('Bordeaux / Supérieur',1,{regio:'bordeaux',app:['Bordeaux','Bordeaux Supérieur']}),
    S('Médoc',1,{regio:'bordeaux',app:['Médoc']}),
    S('Haut-Médoc',1,{regio:'bordeaux',app:['Haut-Médoc']}),
    S('Saint-Émilion',1,{regio:'bordeaux',app:['Saint-Émilion','Saint-Émilion Grand Cru']}),
    S('Pessac-Léognan',2,{regio:'bordeaux',app:['Pessac-Léognan','Graves']}),
    S('Margaux',2,{regio:'bordeaux',app:['Margaux']}),
    S('Pauillac',2,{regio:'bordeaux',app:['Pauillac']}),
    S('Pomerol',3,{regio:'bordeaux',app:['Pomerol']}),
    S('Sauternes',2,{regio:'bordeaux',app:['Sauternes','Barsac']})]},
  {id:'bordeaux-2',name:'Bordeaux II',part:1,land:'Frankrijk',area:'bordeaux',unlock:'bordeaux-1',slots:[
    S('Côtes de Bourg',2,{regio:'bordeaux',app:['Côtes de Bourg']}),
    S('Blaye',2,{regio:'bordeaux',app:['Blaye','Blaye Côtes de Bordeaux']}),
    S('Fronsac',2,{regio:'bordeaux',app:['Fronsac','Canon-Fronsac']}),
    S('Lalande-de-Pomerol',2,{regio:'bordeaux',app:['Lalande-de-Pomerol']}),
    S('Listrac-Médoc',3,{regio:'bordeaux',app:['Listrac-Médoc']}),
    S('Moulis',3,{regio:'bordeaux',app:['Moulis','Moulis-en-Médoc']}),
    S('Saint-Julien',2,{regio:'bordeaux',app:['Saint-Julien']}),
    S('Saint-Estèphe',2,{regio:'bordeaux',app:['Saint-Estèphe']}),
    S('Entre-Deux-Mers',2,{regio:'bordeaux',app:['Entre-Deux-Mers']})]},
  {id:'bourgogne-1',name:'Bourgogne I',part:1,land:'Frankrijk',area:'bourgogne',slots:[
    S('Bourgogne',1,{regio:'bourgogne',app:['Bourgogne','Bourgogne AOC','Bourgogne Côte d\'Or']}),
    S('Mâcon',1,{regio:'bourgogne',app:['Mâcon','Mâcon-Villages']}),
    S('Chablis',1,{regio:'bourgogne',app:['Chablis']}),
    S('Givry / Mercurey',2,{regio:'bourgogne',app:['Givry','Mercurey']}),
    S('Crémant de Bourgogne',2,{regio:'bourgogne',app:['Crémant de Bourgogne']}),
    S('Pouilly-Fuissé',2,{regio:'bourgogne',app:['Pouilly-Fuissé']}),
    S('Côte de Nuits-Villages',2,{regio:'bourgogne',app:['Côte de Nuits-Villages']}),
    S('Gevrey-Chambertin',3,{regio:'bourgogne',app:['Gevrey-Chambertin']}),
    S('Meursault',3,{regio:'bourgogne',app:['Meursault']})]},
  {id:'bourgogne-2',name:'Bourgogne II',part:1,land:'Frankrijk',area:'bourgogne',unlock:'bourgogne-1',slots:[
    S('Rully',2,{regio:'bourgogne',app:['Rully']}),
    S('Montagny',2,{regio:'bourgogne',app:['Montagny']}),
    S('Santenay',2,{regio:'bourgogne',app:['Santenay']}),
    S('Savigny-lès-Beaune',2,{regio:'bourgogne',app:['Savigny-lès-Beaune']}),
    S('Pommard',3,{regio:'bourgogne',app:['Pommard']}),
    S('Volnay',3,{regio:'bourgogne',app:['Volnay']}),
    S('Nuits-Saint-Georges',3,{regio:'bourgogne',app:['Nuits-Saint-Georges']}),
    S('Vosne-Romanée',3,{regio:'bourgogne',app:['Vosne-Romanée','Romanée-Conti Grand Cru']}),
    S('Chablis Premier Cru',2,{regio:'bourgogne',app:['Chablis Premier Cru']})]},
  {id:'beaujolais',name:'Beaujolais',part:1,land:'Frankrijk',area:'beaujolais',slots:[
    S('Beaujolais',1,{regio:'beaujolais',app:['Beaujolais']}),
    S('Beaujolais-Villages',1,{regio:'beaujolais',app:['Beaujolais-Villages']}),
    S('Morgon',2,{regio:'beaujolais',app:['Morgon']}),
    S('Fleurie',2,{regio:'beaujolais',app:['Fleurie']}),
    S('Moulin-à-Vent',2,{regio:'beaujolais',app:['Moulin-à-Vent']}),
    S('Brouilly',2,{regio:'beaujolais',app:['Brouilly','Côte de Brouilly']}),
    S('Juliénas',2,{regio:'beaujolais',app:['Juliénas']}),
    S('Saint-Amour',3,{regio:'beaujolais',app:['Saint-Amour']}),
    S('Chiroubles',3,{regio:'beaujolais',app:['Chiroubles']})]},
  {id:'rhone',name:'Rhône',part:1,land:'Frankrijk',area:'rhone',slots:[
    S('Côtes du Rhône',1,{regio:'rhone',app:['Côtes du Rhône']}),
    S('Côtes du Rhône Villages',1,{regio:'rhone',app:['Côtes du Rhône Villages']}),
    S('Ventoux / Luberon',1,{regio:'rhone',app:['Ventoux','Luberon']}),
    S('Vacqueyras',2,{regio:'rhone',app:['Vacqueyras']}),
    S('Gigondas',2,{regio:'rhone',app:['Gigondas']}),
    S('Châteauneuf-du-Pape',2,{regio:'rhone',app:['Châteauneuf-du-Pape']}),
    S('Crozes-Hermitage',2,{regio:'rhone',app:['Crozes-Hermitage']}),
    S('Saint-Joseph',2,{regio:'rhone',app:['Saint-Joseph']}),
    S('Condrieu',3,{regio:'rhone',app:['Condrieu']})]},
  {id:'loire',name:'Loire',part:1,land:'Frankrijk',area:'loire',slots:[
    S('Muscadet',1,{regio:'loire',app:['Muscadet','Muscadet Sèvre et Maine']}),
    S('Touraine',1,{regio:'loire',app:['Touraine']}),
    S('Vouvray',2,{regio:'loire',app:['Vouvray']}),
    S('Sancerre',1,{regio:'loire',app:['Sancerre']}),
    S('Pouilly-Fumé',2,{regio:'loire',app:['Pouilly-Fumé']}),
    S('Anjou / Saumur',2,{regio:'loire',app:['Anjou','Saumur','Saumur-Champigny']}),
    S('Chinon / Bourgueil',2,{regio:'loire',app:['Chinon','Bourgueil']}),
    S('Crémant de Loire',2,{regio:'loire',app:['Crémant de Loire']}),
    S('Savennières',3,{regio:'loire',app:['Savennières']})]},
  {id:'jura',name:'Jura',part:1,land:'Frankrijk',area:'jura',secret:true,slots:[
    S('Côtes du Jura',2,{regio:'jura',app:['Côtes du Jura']}),
    S('Arbois',2,{regio:'jura',app:['Arbois']}),
    S('Crémant du Jura',2,{regio:'jura',app:['Crémant du Jura']}),
    S('L\'Étoile',3,{regio:'jura',app:['L\'Étoile']}),
    S('Château-Chalon',3,{regio:'jura',app:['Château-Chalon']}),
    S('Vin Jaune',3,{regio:'jura',tag:'vin jaune'})]},
  {id:'champagne',name:'Champagne',part:1,land:'Frankrijk',slots:[
    S('Brut',1,{regio:'champagne',tag:'brut'}),
    S('Blanc de Blancs',2,{regio:'champagne',tag:'blanc de blancs'}),
    S('Blanc de Noirs',2,{regio:'champagne',tag:'blanc de noirs'}),
    S('Rosé',2,{regio:'champagne',color:'rosé'}),
    S('Extra Brut / Brut Nature',2,{regio:'champagne',tag:'brut nature'}),
    S('Millésime',3,{regio:'champagne',tag:'millésime'}),
    S('Prestige cuvée',3,{regio:'champagne',tag:'prestige'}),
    S('Récoltant-manipulant',3,{regio:'champagne',tag:'récoltant'}),
    S('Coteaux Champenois',3,{regio:'champagne',app:['Coteaux Champenois']})]},
  {id:'elzas',name:'Elzas',part:1,land:'Frankrijk',slots:[
    S('Riesling',1,{regio:'elzas',grape:'Riesling'}),
    S('Gewurztraminer',1,{regio:'elzas',grape:'Gewurztraminer'}),
    S('Pinot Gris',1,{regio:'elzas',grape:'Pinot Gris'}),
    S('Pinot Blanc',1,{regio:'elzas',grape:'Pinot Blanc'}),
    S('Crémant d\'Alsace',1,{regio:'elzas',app:['Crémant d\'Alsace']}),
    S('Muscat',2,{regio:'elzas',grape:'Muscat'}),
    S('Pinot Noir',2,{regio:'elzas',grape:'Pinot Noir'}),
    S('Grand Cru',3,{regio:'elzas',tag:'grand cru'}),
    S('Vendanges Tardives',3,{regio:'elzas',tag:'vendanges tardives'})]},
  {id:'languedoc',name:'Languedoc-Roussillon',part:1,land:'Frankrijk',slots:[
    S('Pays d\'Oc',1,{land:'Frankrijk',app:['Pays d\'Oc','IGP Pays d\'Oc']}),
    S('Languedoc',1,{land:'Frankrijk',app:['Languedoc','Coteaux du Languedoc']}),
    S('Corbières',1,{land:'Frankrijk',app:['Corbières']}),
    S('Minervois',1,{land:'Frankrijk',app:['Minervois']}),
    S('Picpoul de Pinet',1,{land:'Frankrijk',app:['Picpoul de Pinet']}),
    S('Saint-Chinian',2,{land:'Frankrijk',app:['Saint-Chinian']}),
    S('Faugères',2,{land:'Frankrijk',app:['Faugères']}),
    S('Pic Saint-Loup',2,{land:'Frankrijk',app:['Pic Saint-Loup']}),
    S('Côtes du Roussillon',2,{land:'Frankrijk',app:['Côtes du Roussillon','Côtes du Roussillon Villages']})]},
  {id:'provence',name:'Provence',part:1,land:'Frankrijk',slots:[
    S('Côtes de Provence',1,{land:'Frankrijk',app:['Côtes de Provence']}),
    S('Coteaux d\'Aix-en-Provence',1,{land:'Frankrijk',app:['Coteaux d\'Aix-en-Provence']}),
    S('Méditerranée',1,{land:'Frankrijk',app:['Méditerranée','IGP Méditerranée']}),
    S('Coteaux Varois',2,{land:'Frankrijk',app:['Coteaux Varois en Provence','Coteaux Varois']}),
    S('Bandol',2,{land:'Frankrijk',app:['Bandol']}),
    S('Sainte-Victoire',3,{land:'Frankrijk',app:['Côtes de Provence Sainte-Victoire']}),
    S('Cassis',3,{land:'Frankrijk',app:['Cassis']}),
    S('Bellet',3,{land:'Frankrijk',app:['Bellet']}),
    S('Palette',3,{land:'Frankrijk',app:['Palette']})]},
  {id:'zuidwest',name:'Zuidwest-Frankrijk',part:1,land:'Frankrijk',slots:[
    S('Côtes de Gascogne',1,{land:'Frankrijk',app:['Côtes de Gascogne','IGP Côtes de Gascogne']}),
    S('Bergerac',1,{land:'Frankrijk',app:['Bergerac']}),
    S('Cahors',1,{land:'Frankrijk',app:['Cahors']}),
    S('Madiran',2,{land:'Frankrijk',app:['Madiran']}),
    S('Jurançon',2,{land:'Frankrijk',app:['Jurançon']}),
    S('Monbazillac',2,{land:'Frankrijk',app:['Monbazillac']}),
    S('Gaillac',2,{land:'Frankrijk',app:['Gaillac']}),
    S('Fronton',3,{land:'Frankrijk',app:['Fronton']}),
    S('Irouléguy',3,{land:'Frankrijk',app:['Irouléguy']})]},
  {id:'toscane',name:'Toscane',part:1,land:'Italië',area:'toscane',slots:[
    S('Toscana IGT',1,{regio:'toscane',app:['Toscana IGT']}),
    S('Chianti',1,{regio:'toscane',app:['Chianti']}),
    S('Chianti Classico',1,{regio:'toscane',app:['Chianti Classico']}),
    S('Morellino di Scansano',2,{regio:'toscane',app:['Morellino di Scansano']}),
    S('Rosso di Montalcino',2,{regio:'toscane',app:['Rosso di Montalcino']}),
    S('Vino Nobile di Montepulciano',2,{regio:'toscane',app:['Vino Nobile di Montepulciano']}),
    S('Vernaccia di San Gimignano',2,{regio:'toscane',app:['Vernaccia di San Gimignano']}),
    S('Brunello di Montalcino',3,{regio:'toscane',app:['Brunello di Montalcino']}),
    S('Bolgheri',3,{regio:'toscane',app:['Bolgheri','Bolgheri Sassicaia']})]},
  {id:'piemonte',name:'Piemonte',part:1,land:'Italië',slots:[
    S('Barbera d\'Asti',1,{land:'Italië',app:['Barbera d\'Asti']}),
    S('Langhe',1,{land:'Italië',app:['Langhe','Langhe Nebbiolo']}),
    S('Gavi',1,{land:'Italië',app:['Gavi','Gavi di Gavi']}),
    S('Moscato d\'Asti',1,{land:'Italië',app:['Moscato d\'Asti','Asti']}),
    S('Barbera d\'Alba',2,{land:'Italië',app:['Barbera d\'Alba']}),
    S('Dolcetto d\'Alba',2,{land:'Italië',app:['Dolcetto d\'Alba']}),
    S('Barolo',2,{land:'Italië',app:['Barolo']}),
    S('Barbaresco',2,{land:'Italië',app:['Barbaresco']}),
    S('Roero',3,{land:'Italië',app:['Roero','Roero Arneis']})]},
  {id:'veneto',name:'Veneto',part:1,land:'Italië',slots:[
    S('Prosecco',1,{land:'Italië',app:['Prosecco','Prosecco Superiore','Conegliano Valdobbiadene']}),
    S('Valpolicella',1,{land:'Italië',app:['Valpolicella','Valpolicella Classico']}),
    S('Ripasso',1,{land:'Italië',app:['Valpolicella Ripasso']}),
    S('Soave',1,{land:'Italië',app:['Soave','Soave Classico']}),
    S('Bardolino',1,{land:'Italië',app:['Bardolino']}),
    S('Pinot Grigio delle Venezie',1,{land:'Italië',app:['Pinot Grigio delle Venezie','Delle Venezie']}),
    S('Amarone',2,{land:'Italië',app:['Amarone della Valpolicella']}),
    S('Lugana',2,{land:'Italië',app:['Lugana']}),
    S('Recioto',3,{land:'Italië',app:['Recioto della Valpolicella','Recioto di Soave']})]},
  {id:'zuid-italie',name:'Zuid-Italië',part:1,land:'Italië',slots:[
    S('Primitivo di Manduria',1,{land:'Italië',app:['Primitivo di Manduria']}),
    S('Puglia',1,{land:'Italië',app:['Puglia','IGT Puglia']}),
    S('Salento',1,{land:'Italië',app:['Salento','IGT Salento']}),
    S('Salice Salentino',1,{land:'Italië',app:['Salice Salentino']}),
    S('Montepulciano d\'Abruzzo',1,{land:'Italië',app:['Montepulciano d\'Abruzzo']}),
    S('Falanghina',2,{land:'Italië',app:['Falanghina del Sannio','Campania']}),
    S('Aglianico del Vulture',3,{land:'Italië',app:['Aglianico del Vulture']}),
    S('Taurasi',3,{land:'Italië',app:['Taurasi']}),
    S('Cirò',3,{land:'Italië',app:['Cirò']})]},
  {id:'sicilie',name:'Sicilië',part:1,land:'Italië',slots:[
    S('Terre Siciliane',1,{land:'Italië',app:['Terre Siciliane']}),
    S('Sicilia',1,{land:'Italië',app:['Sicilia']}),
    S('Etna Rosso',2,{land:'Italië',app:['Etna','Etna Rosso'],color:'rood'}),
    S('Etna Bianco',2,{land:'Italië',app:['Etna','Etna Bianco'],color:'wit'}),
    S('Cerasuolo di Vittoria',2,{land:'Italië',app:['Cerasuolo di Vittoria']}),
    S('Marsala',2,{land:'Italië',app:['Marsala']}),
    S('Pantelleria',3,{land:'Italië',app:['Pantelleria','Passito di Pantelleria']}),
    S('Noto',3,{land:'Italië',app:['Noto']}),
    S('Faro',3,{land:'Italië',app:['Faro']})]},
  {id:'rioja',name:'Rioja',part:1,land:'Spanje',area:'rioja',slots:[
    S('Rioja (joven)',1,{regio:'rioja',tag:'joven'}),
    S('Crianza',1,{regio:'rioja',tag:'crianza'}),
    S('Reserva',1,{regio:'rioja',tag:'reserva'}),
    S('Gran Reserva',2,{regio:'rioja',tag:'gran reserva'}),
    S('Rioja Blanco',1,{regio:'rioja',color:'wit'}),
    S('Rioja Rosado',2,{regio:'rioja',color:'rosé'}),
    S('Rioja Alta',2,{regio:'rioja',tag:'rioja alta'}),
    S('Rioja Alavesa',2,{regio:'rioja',tag:'rioja alavesa'}),
    S('Rioja Oriental',3,{regio:'rioja',tag:'rioja oriental'})]},
  {id:'noordwest-spanje',name:'Noordwest-Spanje',part:1,land:'Spanje',slots:[
    S('Ribera del Duero',1,{land:'Spanje',app:['Ribera del Duero']}),
    S('Rueda',1,{land:'Spanje',app:['Rueda']}),
    S('Navarra',1,{land:'Spanje',app:['Navarra']}),
    S('Rías Baixas',2,{land:'Spanje',app:['Rías Baixas']}),
    S('Toro',2,{land:'Spanje',app:['Toro']}),
    S('Bierzo',2,{land:'Spanje',app:['Bierzo']}),
    S('Ribeiro',3,{land:'Spanje',app:['Ribeiro']}),
    S('Valdeorras',3,{land:'Spanje',app:['Valdeorras']}),
    S('Txakoli',3,{land:'Spanje',app:['Txakoli','Getariako Txakolina']})]},
  {id:'oost-spanje',name:'Oost-Spanje',part:1,land:'Spanje',slots:[
    S('Cava',1,{land:'Spanje',app:['Cava']}),
    S('Penedès',1,{land:'Spanje',app:['Penedès']}),
    S('Jumilla',1,{land:'Spanje',app:['Jumilla']}),
    S('Valencia',1,{land:'Spanje',app:['Valencia']}),
    S('Yecla',2,{land:'Spanje',app:['Yecla']}),
    S('Utiel-Requena',2,{land:'Spanje',app:['Utiel-Requena']}),
    S('Montsant',2,{land:'Spanje',app:['Montsant']}),
    S('Priorat',3,{land:'Spanje',app:['Priorat']}),
    S('Costers del Segre',3,{land:'Spanje',app:['Costers del Segre']})]},
  {id:'centraal-zuid-spanje',name:'Centraal- en Zuid-Spanje',part:1,land:'Spanje',slots:[
    S('Castilla',1,{land:'Spanje',app:['Castilla','Vino de la Tierra de Castilla']}),
    S('La Mancha',1,{land:'Spanje',app:['La Mancha']}),
    S('Valdepeñas',1,{land:'Spanje',app:['Valdepeñas']}),
    S('Sherry',2,{land:'Spanje',app:['Jerez','Jerez-Xérès-Sherry','Sherry']}),
    S('Manzanilla',2,{land:'Spanje',app:['Manzanilla','Manzanilla-Sanlúcar de Barrameda']}),
    S('Málaga',3,{land:'Spanje',app:['Málaga']}),
    S('Montilla-Moriles',3,{land:'Spanje',app:['Montilla-Moriles']}),
    S('Vinos de Madrid',3,{land:'Spanje',app:['Vinos de Madrid']}),
    S('Manchuela',3,{land:'Spanje',app:['Manchuela']})]},
  {id:'nieuw-zeeland',name:'Nieuw-Zeeland',part:1,land:'Nieuw-Zeeland',area:'nieuw-zeeland',slots:[
    S('Marlborough',1,{land:'Nieuw-Zeeland',app:['Marlborough']}),
    S('Hawke\'s Bay',2,{land:'Nieuw-Zeeland',app:['Hawke\'s Bay']}),
    S('Central Otago',2,{land:'Nieuw-Zeeland',app:['Central Otago']}),
    S('Martinborough',3,{land:'Nieuw-Zeeland',app:['Martinborough','Wairarapa']}),
    S('Nelson',3,{land:'Nieuw-Zeeland',app:['Nelson']}),
    S('Gisborne',3,{land:'Nieuw-Zeeland',app:['Gisborne']}),
    S('North Canterbury',3,{land:'Nieuw-Zeeland',app:['North Canterbury','Waipara']}),
    S('Waiheke / Auckland',3,{land:'Nieuw-Zeeland',app:['Waiheke Island','Auckland']}),
    S('Gimblett Gravels',3,{land:'Nieuw-Zeeland',app:['Gimblett Gravels']})]},

  /* ---------- Overige landen: één set per land, vakken = regio's ---------- */
  {id:'portugal',name:'Portugal',part:1,land:'Portugal',slots:[
    S('Vinho Verde',1,{land:'Portugal',app:['Vinho Verde']}),
    S('Douro',1,{land:'Portugal',app:['Douro']}),
    S('Alentejo',1,{land:'Portugal',app:['Alentejo', 'Alentejano']}),
    S('Lisboa',1,{land:'Portugal',app:['Lisboa']}),
    S('Porto',1,{land:'Portugal',app:['Porto', 'Port']}),
    S('Dão',2,{land:'Portugal',app:['Dão']}),
    S('Bairrada',2,{land:'Portugal',app:['Bairrada']}),
    S('Setúbal',2,{land:'Portugal',app:['Setúbal', 'Península de Setúbal']}),
    S('Madeira',2,{land:'Portugal',app:['Madeira']})]},
  {id:'duitsland',name:'Duitsland',part:1,land:'Duitsland',slots:[
    S('Mosel',1,{land:'Duitsland',app:['Mosel']}),
    S('Pfalz',1,{land:'Duitsland',app:['Pfalz']}),
    S('Rheinhessen',1,{land:'Duitsland',app:['Rheinhessen']}),
    S('Rheingau',2,{land:'Duitsland',app:['Rheingau']}),
    S('Nahe',2,{land:'Duitsland',app:['Nahe']}),
    S('Baden',2,{land:'Duitsland',app:['Baden']}),
    S('Franken',2,{land:'Duitsland',app:['Franken']}),
    S('Württemberg',3,{land:'Duitsland',app:['Württemberg']}),
    S('Ahr',3,{land:'Duitsland',app:['Ahr']})]},
  {id:'oostenrijk',name:'Oostenrijk',part:1,land:'Oostenrijk',slots:[
    S('Weinviertel',1,{land:'Oostenrijk',app:['Weinviertel']}),
    S('Burgenland',1,{land:'Oostenrijk',app:['Burgenland']}),
    S('Wachau',2,{land:'Oostenrijk',app:['Wachau']}),
    S('Kamptal',2,{land:'Oostenrijk',app:['Kamptal']}),
    S('Kremstal',2,{land:'Oostenrijk',app:['Kremstal']}),
    S('Neusiedlersee',2,{land:'Oostenrijk',app:['Neusiedlersee']}),
    S('Steiermark',2,{land:'Oostenrijk',app:['Südsteiermark', 'Steiermark', 'Vulkanland Steiermark', 'Weststeiermark']}),
    S('Wien',3,{land:'Oostenrijk',app:['Wien']}),
    S('Carnuntum',3,{land:'Oostenrijk',app:['Carnuntum']})]},
  {id:'nederland',name:'Nederland',part:1,land:'Nederland',slots:[
    S('Limburg',2,{land:'Nederland',app:['Limburg', 'Maasvallei Limburg', 'Mergelland', 'Vijlen']}),
    S('Gelderland',2,{land:'Nederland',app:['Gelderland']}),
    S('Zeeland',2,{land:'Nederland',app:['Zeeland']}),
    S('Noord-Brabant',2,{land:'Nederland',app:['Noord-Brabant']}),
    S('Utrecht',2,{land:'Nederland',app:['Utrecht', 'Utrechtse Heuvelrug']}),
    S('Overijssel',3,{land:'Nederland',app:['Overijssel', 'Oolde']}),
    S('Noord-Holland',3,{land:'Nederland',app:['Noord-Holland']}),
    S('Zuid-Holland',3,{land:'Nederland',app:['Zuid-Holland']}),
    S('Noorden',3,{land:'Nederland',app:['Friesland', 'Groningen', 'Drenthe']})]},
  {id:'verenigd-koninkrijk',name:'Engeland en Wales',part:1,land:'Verenigd Koninkrijk',slots:[
    S('Sussex',2,{land:'Verenigd Koninkrijk',app:['Sussex']}),
    S('Kent',2,{land:'Verenigd Koninkrijk',app:['Kent']}),
    S('Hampshire',2,{land:'Verenigd Koninkrijk',app:['Hampshire']}),
    S('Surrey',3,{land:'Verenigd Koninkrijk',app:['Surrey']}),
    S('Essex',3,{land:'Verenigd Koninkrijk',app:['Essex']}),
    S('Dorset',3,{land:'Verenigd Koninkrijk',app:['Dorset']}),
    S('Cornwall',3,{land:'Verenigd Koninkrijk',app:['Cornwall']}),
    S('Oxfordshire',3,{land:'Verenigd Koninkrijk',app:['Oxfordshire']}),
    S('Wales',3,{land:'Verenigd Koninkrijk',app:['Wales']})]},
  {id:'zuid-afrika',name:'Zuid-Afrika',part:1,land:'Zuid-Afrika',slots:[
    S('Western Cape',1,{land:'Zuid-Afrika',app:['Western Cape', 'Coastal Region']}),
    S('Stellenbosch',1,{land:'Zuid-Afrika',app:['Stellenbosch']}),
    S('Paarl',1,{land:'Zuid-Afrika',app:['Paarl']}),
    S('Robertson',1,{land:'Zuid-Afrika',app:['Robertson']}),
    S('Swartland',2,{land:'Zuid-Afrika',app:['Swartland']}),
    S('Franschhoek',2,{land:'Zuid-Afrika',app:['Franschhoek']}),
    S('Hemel-en-Aarde',2,{land:'Zuid-Afrika',app:['Hemel-en-Aarde', 'Walker Bay']}),
    S('Elgin',3,{land:'Zuid-Afrika',app:['Elgin']}),
    S('Constantia',3,{land:'Zuid-Afrika',app:['Constantia']})]},
  {id:'chili',name:'Chili',part:1,land:'Chili',slots:[
    S('Valle Central',1,{land:'Chili',app:['Valle Central', 'Central Valley']}),
    S('Maipo',1,{land:'Chili',app:['Maipo']}),
    S('Colchagua',1,{land:'Chili',app:['Colchagua']}),
    S('Casablanca',1,{land:'Chili',app:['Casablanca']}),
    S('Curicó',2,{land:'Chili',app:['Curicó']}),
    S('Cachapoal',2,{land:'Chili',app:['Cachapoal', 'Rapel']}),
    S('Maule',2,{land:'Chili',app:['Maule']}),
    S('Aconcagua',2,{land:'Chili',app:['Aconcagua']}),
    S('Itata',3,{land:'Chili',app:['Itata']})]},
  {id:'argentinie',name:'Argentinië',part:1,land:'Argentinië',slots:[
    S('Mendoza',1,{land:'Argentinië',app:['Mendoza']}),
    S('Luján de Cuyo',2,{land:'Argentinië',app:['Luján de Cuyo']}),
    S('Valle de Uco',2,{land:'Argentinië',app:['Valle de Uco', 'Uco Valley', 'Tupungato']}),
    S('Maipú',2,{land:'Argentinië',app:['Maipú']}),
    S('Salta',2,{land:'Argentinië',app:['Salta', 'Cafayate', 'Calchaquí']}),
    S('San Juan',2,{land:'Argentinië',app:['San Juan']}),
    S('Patagonia',3,{land:'Argentinië',app:['Patagonia', 'Neuquén', 'Río Negro']}),
    S('La Rioja',3,{land:'Argentinië',app:['La Rioja']}),
    S('Catamarca',3,{land:'Argentinië',app:['Catamarca']})]},
  {id:'verenigde-staten',name:'Verenigde Staten',part:1,land:'Verenigde Staten',slots:[
    S('Californië',1,{land:'Verenigde Staten',app:['California', 'Californië']}),
    S('Napa Valley',1,{land:'Verenigde Staten',app:['Napa Valley']}),
    S('Sonoma',1,{land:'Verenigde Staten',app:['Sonoma', 'Sonoma Coast', 'Sonoma County']}),
    S('Lodi',1,{land:'Verenigde Staten',app:['Lodi']}),
    S('Paso Robles',2,{land:'Verenigde Staten',app:['Paso Robles']}),
    S('Santa Barbara',3,{land:'Verenigde Staten',app:['Santa Barbara', 'Santa Rita Hills']}),
    S('Oregon',2,{land:'Verenigde Staten',app:['Willamette Valley', 'Oregon']}),
    S('Washington State',2,{land:'Verenigde Staten',app:['Columbia Valley', 'Washington State', 'Walla Walla']}),
    S('New York',3,{land:'Verenigde Staten',app:['Finger Lakes', 'New York']})]},
  {id:'australie',name:'Australië',part:1,land:'Australië',slots:[
    S('South Eastern Australia',1,{land:'Australië',app:['South Eastern Australia', 'South Australia']}),
    S('Barossa Valley',1,{land:'Australië',app:['Barossa Valley', 'Barossa']}),
    S('McLaren Vale',2,{land:'Australië',app:['McLaren Vale']}),
    S('Coonawarra',2,{land:'Australië',app:['Coonawarra']}),
    S('Margaret River',2,{land:'Australië',app:['Margaret River']}),
    S('Yarra Valley',2,{land:'Australië',app:['Yarra Valley']}),
    S('Hunter Valley',2,{land:'Australië',app:['Hunter Valley']}),
    S('Clare / Eden Valley',3,{land:'Australië',app:['Clare Valley', 'Eden Valley']}),
    S('Tasmanië',3,{land:'Australië',app:['Tasmania', 'Tasmanië']})]},

  /* ---------- Deel 2: verzamellijsten ---------- */
  {id:'starter',name:'De Grote Vijf',part:2,always:true,intro:'Je eerste set. Vijf druiven die je overal tegenkomt.',slots:[
    S('Cabernet Sauvignon',1,{grape:'Cabernet Sauvignon'}),
    S('Merlot',1,{grape:'Merlot'}),
    S('Pinot Noir',1,{grape:'Pinot Noir'}),
    S('Chardonnay',1,{grape:'Chardonnay'}),
    S('Sauvignon Blanc',1,{grape:'Sauvignon Blanc'})]},
  {id:'wereldreiziger',name:'Wereldreiziger',part:2,always:true,intro:'Eén wijn uit elk land.',slots:
    ['Frankrijk','Italië','Spanje','Portugal','Duitsland','Nederland','Zuid-Afrika','Chili','Argentinië','Verenigde Staten','Australië','Nieuw-Zeeland']
      .map(l=>S(l,['Nederland','Portugal','Argentinië'].includes(l)?2:1,{land:l}))},
  {id:'chardonnay',name:'Chardonnay rond de wereld',part:2,slots:[
    S('Bourgogne',1,{grape:'Chardonnay',regio:'bourgogne'}),
    S('Chablis',1,{grape:'Chardonnay',app:['Chablis','Chablis Premier Cru']}),
    S('Jura',2,{grape:'Chardonnay',regio:'jura'}),
    S('Champagne',2,{grape:'Chardonnay',regio:'champagne'}),
    S('Californië',1,{grape:'Chardonnay',regio:'californie'}),
    S('Australië',1,{grape:'Chardonnay',land:'Australië'}),
    S('Zuid-Afrika',1,{grape:'Chardonnay',land:'Zuid-Afrika'}),
    S('Chili',1,{grape:'Chardonnay',land:'Chili'}),
    S('Nieuw-Zeeland',2,{grape:'Chardonnay',land:'Nieuw-Zeeland'})]},
  {id:'wereldreiziger-2',name:'Wereldreiziger II',part:2,unlock:'wereldreiziger',intro:'Vrijgespeeld! Twaalf wijnlanden buiten de gebaande paden.',slots:
    ['Griekenland','Hongarije','Georgië','Libanon','Uruguay','België','Zwitserland','Canada','Japan','Israël','Kroatië','Luxemburg']
      .map(l=>S(l,['België','Luxemburg','Griekenland','Hongarije'].includes(l)?2:3,{land:l}))},
  {id:'pinot-noir',name:'Pinot Noir rond de wereld',part:2,slots:[
    S('Bourgogne',1,{grape:'Pinot Noir',regio:'bourgogne'}),
    S('Elzas',2,{grape:'Pinot Noir',regio:'elzas'}),
    S('Duitsland',2,{grape:'Pinot Noir',land:'Duitsland'}),
    S('Italië',2,{grape:'Pinot Noir',land:'Italië'}),
    S('Oregon',3,{grape:'Pinot Noir',regio:'oregon'}),
    S('Californië',2,{grape:'Pinot Noir',regio:'californie'}),
    S('Nieuw-Zeeland',1,{grape:'Pinot Noir',land:'Nieuw-Zeeland'}),
    S('Chili',1,{grape:'Pinot Noir',land:'Chili'}),
    S('Zuid-Afrika',2,{grape:'Pinot Noir',land:'Zuid-Afrika'})]},
  {id:'sauvignon-blanc',name:'Sauvignon Blanc rond de wereld',part:2,slots:[
    S('Sancerre',1,{grape:'Sauvignon Blanc',app:['Sancerre']}),
    S('Pouilly-Fumé',2,{grape:'Sauvignon Blanc',app:['Pouilly-Fumé']}),
    S('Touraine',1,{grape:'Sauvignon Blanc',app:['Touraine']}),
    S('Bordeaux Blanc',1,{grape:'Sauvignon Blanc',regio:'bordeaux'}),
    S('Oostenrijk',2,{grape:'Sauvignon Blanc',land:'Oostenrijk'}),
    S('Marlborough',1,{grape:'Sauvignon Blanc',app:['Marlborough']}),
    S('Zuid-Afrika',1,{grape:'Sauvignon Blanc',land:'Zuid-Afrika'}),
    S('Chili',1,{grape:'Sauvignon Blanc',land:'Chili'}),
    S('Australië',2,{grape:'Sauvignon Blanc',land:'Australië'})]},
  {id:'syrah',name:'Syrah / Shiraz rond de wereld',part:2,slots:[
    S('Noordelijke Rhône',2,{grape:'Syrah',app:['Crozes-Hermitage','Saint-Joseph','Hermitage','Côte-Rôtie','Cornas']}),
    S('Languedoc',1,{grape:'Syrah',regio:'languedoc'}),
    S('Australië',1,{grape:'Syrah',land:'Australië'}),
    S('Zuid-Afrika',1,{grape:'Syrah',land:'Zuid-Afrika'}),
    S('Chili',1,{grape:'Syrah',land:'Chili'}),
    S('Californië',2,{grape:'Syrah',regio:'californie'}),
    S('Washington State',3,{grape:'Syrah',regio:'washington'}),
    S('Nieuw-Zeeland',2,{grape:'Syrah',land:'Nieuw-Zeeland'}),
    S('Argentinië',2,{grape:'Syrah',land:'Argentinië'})]},
  {id:'cabernet',name:'Cabernet Sauvignon rond de wereld',part:2,slots:[
    S('Bordeaux linkeroever',1,{grape:'Cabernet Sauvignon',regio:'bordeaux',app:['Médoc','Haut-Médoc','Pauillac','Margaux','Saint-Julien','Saint-Estèphe','Pessac-Léognan','Listrac-Médoc','Moulis']}),
    S('Toscane',2,{grape:'Cabernet Sauvignon',regio:'toscane'}),
    S('Spanje',2,{grape:'Cabernet Sauvignon',land:'Spanje'}),
    S('Californië',1,{grape:'Cabernet Sauvignon',regio:'californie'}),
    S('Washington State',3,{grape:'Cabernet Sauvignon',regio:'washington'}),
    S('Chili',1,{grape:'Cabernet Sauvignon',land:'Chili'}),
    S('Argentinië',2,{grape:'Cabernet Sauvignon',land:'Argentinië'}),
    S('Australië',1,{grape:'Cabernet Sauvignon',land:'Australië'}),
    S('Zuid-Afrika',1,{grape:'Cabernet Sauvignon',land:'Zuid-Afrika'})]},
  {id:'bubbels',name:'Bubbels',part:2,slots:[
    S('Champagne',1,{app:['Champagne']}),
    S('Crémant',1,{tag:'crémant'}),
    S('Cava',1,{app:['Cava']}),
    S('Prosecco',1,{app:['Prosecco']}),
    S('Franciacorta',2,{app:['Franciacorta']}),
    S('Sekt',2,{style:'mousserend',land:'Duitsland'}),
    S('Cap Classique',2,{style:'mousserend',land:'Zuid-Afrika'}),
    S('Engelse bubbels',3,{style:'mousserend',land:'Verenigd Koninkrijk'}),
    S('Pét-nat',3,{tag:'pét-nat'})]},
  {id:'icons',name:'Icons',part:2,always:true,intro:'Twaalf legendarische wijnen. Vaak per glas te proeven.',slots:[
    S('Cloudy Bay Sauvignon Blanc',2,{key:'cloudy bay|cloudy bay sauvignon blanc'}),
    S('Tignanello',2,{key:'marchesi antinori|tignanello'}),
    S('Dom Pérignon',2,{key:'moët & chandon|dom pérignon'}),
    S('Krug Grande Cuvée',3,{key:'krug|krug grande cuvée'}),
    S('Sassicaia',3,{key:'tenuta san guido|sassicaia'}),
    S('Vega Sicilia Único',3,{key:'vega sicilia|vega sicilia único'}),
    S('Château d\'Yquem',3,{key:'château d\'yquem|château d\'yquem'}),
    S('Penfolds Grange',3,{key:'penfolds|penfolds grange'}),
    S('Opus One',3,{key:'opus one|opus one'}),
    S('Château Margaux',3,{key:'château margaux|château margaux'}),
    S('Pétrus',3,{key:'pétrus|pétrus'}),
    S('Romanée-Conti',3,{key:'domaine de la romanée-conti|romanée-conti'})]}
];

/* ---------- Demowijnen (fase 2) ----------
   De eerste 30 bestonden al; naam en maker blijven gelijk zodat bestaande kaarten blijven kloppen.
   Icons zijn echte wijnen; al het andere is fictief. */
const D=(regio,land,naam,maker,jaar,druif,grape,app,stijl,style,color,tags,icon)=>({regio,land,naam,maker,jaar,druif,grape,app,stijl,style,color,tags:tags||[],icon:!!icon});
const POOL = [
  D('bordeaux','Frankrijk','Château Lamothe-Sablon','Bordeaux Supérieur',2019,'Merlot, Cabernet Franc','Merlot','Bordeaux Supérieur','Rood, soepel','stil','rood'),
  D('bordeaux','Frankrijk','Clos des Graves Pâles','Graves',2021,'Sauvignon Blanc, Sémillon','Sauvignon Blanc','Graves','Wit, fris','stil','wit'),
  D('bordeaux','Frankrijk','Château Belair-Roque','Saint-Émilion Grand Cru',2018,'Merlot','Merlot','Saint-Émilion Grand Cru','Rood, vol','stil','rood'),
  D('bordeaux','Frankrijk','Les Hauts de Ferrand','Médoc',2020,'Cabernet Sauvignon','Cabernet Sauvignon','Médoc','Rood, stevig','stil','rood'),
  D('bordeaux','Frankrijk','Château du Pin Doré','Pauillac',2016,'Cabernet Sauvignon, Merlot','Cabernet Sauvignon','Pauillac','Rood, krachtig','stil','rood'),
  D('bourgogne','Frankrijk','Vernier-Lacombe Pinot Noir','Bourgogne AOC',2021,'Pinot Noir','Pinot Noir','Bourgogne','Rood, licht','stil','rood'),
  D('bourgogne','Frankrijk','Mâcon-Villages Les Crays','Domaine des Crays',2022,'Chardonnay','Chardonnay','Mâcon-Villages','Wit, rond','stil','wit'),
  D('bourgogne','Frankrijk','Chablis Les Bastions','Domaine Morel-Vaudé',2022,'Chardonnay','Chardonnay','Chablis','Wit, mineraal','stil','wit'),
  D('bourgogne','Frankrijk','Clos Ravel','Côte de Nuits-Villages',2020,'Pinot Noir','Pinot Noir','Côte de Nuits-Villages','Rood, elegant','stil','rood'),
  D('bourgogne','Frankrijk','Brut Perle','Crémant de Bourgogne',2021,'Chardonnay, Pinot Noir','','Crémant de Bourgogne','Mousserend, droog','mousserend','wit',['crémant']),
  D('jura','Frankrijk','Domaine des Sapins','Côtes du Jura',2022,'Chardonnay','Chardonnay','Côtes du Jura','Wit, mineraal','stil','wit'),
  D('jura','Frankrijk','Ploussard des Combes','Arbois',2021,'Poulsard','Poulsard','Arbois','Rood, heel licht','stil','rood'),
  D('jura','Frankrijk','Vin Jaune Les Roches','Château-Chalon',2015,'Savagnin','Savagnin','Château-Chalon','Wit, oxidatief','stil','wit',['vin jaune']),
  D('jura','Frankrijk','Trousseau du Moulin','Arbois',2020,'Trousseau','Trousseau','Arbois','Rood, licht','stil','rood'),
  D('jura','Frankrijk','Givre','Crémant du Jura',2021,'Chardonnay','Chardonnay','Crémant du Jura','Mousserend, fris','mousserend','wit',['crémant']),
  D('toscane','Italië','Poggio Alto','Chianti Classico',2020,'Sangiovese','Sangiovese','Chianti Classico','Rood, stevig','stil','rood'),
  D('toscane','Italië','Sassorosso','Toscana IGT',2019,'Cabernet Sauvignon, Merlot','Cabernet Sauvignon','Toscana IGT','Rood, vol','stil','rood'),
  D('toscane','Italië','Casa Rondine','Rosso di Montalcino',2021,'Sangiovese','Sangiovese','Rosso di Montalcino','Rood, elegant','stil','rood'),
  D('toscane','Italië','Vigna del Falco','Brunello di Montalcino',2017,'Sangiovese','Sangiovese','Brunello di Montalcino','Rood, krachtig','stil','rood'),
  D('toscane','Italië','Bianco delle Colline','Toscana IGT',2023,'Vermentino','Vermentino','Toscana IGT','Wit, fris','stil','wit'),
  D('rioja','Spanje','Bodegas Ventura Crianza','Rioja DOCa',2020,'Tempranillo','Tempranillo','Rioja','Rood, houtgerijpt','stil','rood',['crianza']),
  D('rioja','Spanje','Viña Clara Blanco','Rioja DOCa',2022,'Viura','Viura','Rioja','Wit, fris','stil','wit'),
  D('rioja','Spanje','Marqués de Alcor Reserva','Rioja DOCa',2016,'Tempranillo, Graciano','Tempranillo','Rioja','Rood, rijp','stil','rood',['reserva','rioja alta']),
  D('rioja','Spanje','Rosado de la Sierra','Rioja DOCa',2023,'Garnacha','Garnacha','Rioja','Rosé, sappig','stil','rosé'),
  D('rioja','Spanje','Cuatro Vientos Gran Reserva','Rioja DOCa',2012,'Tempranillo','Tempranillo','Rioja','Rood, complex','stil','rood',['gran reserva']),
  D('nieuw-zeeland','Nieuw-Zeeland','Kowhai Bay','Marlborough',2023,'Sauvignon Blanc','Sauvignon Blanc','Marlborough','Wit, uitbundig','stil','wit'),
  D('nieuw-zeeland','Nieuw-Zeeland','Wairau Stone','Marlborough',2022,'Pinot Noir','Pinot Noir','Marlborough','Rood, sappig','stil','rood'),
  D('nieuw-zeeland','Nieuw-Zeeland','Cloudy Ridge','Marlborough',2023,'Pinot Noir','Pinot Noir','Marlborough','Rosé, droog','stil','rosé'),
  D('nieuw-zeeland','Nieuw-Zeeland','Tui Valley','Marlborough',2022,'Chardonnay','Chardonnay','Marlborough','Wit, romig','stil','wit'),
  D('nieuw-zeeland','Nieuw-Zeeland','Awatere Flint','Marlborough',2023,'Sauvignon Blanc','Sauvignon Blanc','Marlborough','Wit, strak','stil','wit'),
  /* nieuw toegevoegd */
  D('bordeaux','Frankrijk','Château Margelle','Château Margelle',2018,'Cabernet Sauvignon, Merlot','Cabernet Sauvignon','Margaux','Rood, elegant','stil','rood'),
  D('bordeaux','Frankrijk','Clos du Tertre','Clos du Tertre',2017,'Merlot','Merlot','Pomerol','Rood, fluweelzacht','stil','rood'),
  D('bordeaux','Frankrijk','Château Lusseau','Château Lusseau',2019,'Cabernet Sauvignon, Merlot','Cabernet Sauvignon','Pessac-Léognan','Rood, rokerig','stil','rood'),
  D('bordeaux','Frankrijk','Château Doisy-Laurent','Château Doisy-Laurent',2015,'Sémillon','Sémillon','Sauternes','Wit, zoet','zoet','wit'),
  D('bordeaux','Frankrijk','Château Rive Haute','Château Rive Haute',2020,'Cabernet Sauvignon','Cabernet Sauvignon','Haut-Médoc','Rood, stevig','stil','rood'),
  D('bordeaux','Frankrijk','Château Bel-Fronsac','Château Bel-Fronsac',2019,'Merlot','Merlot','Fronsac','Rood, rond','stil','rood'),
  D('beaujolais','Frankrijk','Domaine des Pierres Dorées','Domaine des Pierres Dorées',2023,'Gamay','Gamay','Beaujolais','Rood, fruitig','stil','rood'),
  D('beaujolais','Frankrijk','Domaine de la Côte','Domaine de la Côte',2023,'Gamay','Gamay','Beaujolais-Villages','Rood, sappig','stil','rood'),
  D('beaujolais','Frankrijk','Les Granits Roses','Domaine Vernay',2022,'Gamay','Gamay','Morgon','Rood, stevig','stil','rood'),
  D('beaujolais','Frankrijk','Clos des Vignes Fleuries','Domaine Aubel',2022,'Gamay','Gamay','Fleurie','Rood, bloemig','stil','rood'),
  D('beaujolais','Frankrijk','Vent du Moulin','Château des Ailes',2021,'Gamay','Gamay','Moulin-à-Vent','Rood, vol','stil','rood'),
  D('bourgogne','Frankrijk','Pouilly-Fuissé Vieilles Vignes','Domaine Ferrand-Aubert',2021,'Chardonnay','Chardonnay','Pouilly-Fuissé','Wit, rijk','stil','wit'),
  D('bourgogne','Frankrijk','Givry Clos Lavigne','Domaine Lavigne',2021,'Pinot Noir','Pinot Noir','Givry','Rood, kersig','stil','rood'),
  D('rhone','Frankrijk','Les Galets Ronds','Les Galets Ronds',2022,'Grenache, Syrah','Grenache','Côtes du Rhône','Rood, kruidig','stil','rood'),
  D('rhone','Frankrijk','Domaine du Mistral','Domaine du Mistral',2021,'Grenache, Syrah','Grenache','Côtes du Rhône Villages','Rood, warm','stil','rood'),
  D('rhone','Frankrijk','Clos des Papes Anciens','Clos des Papes Anciens',2019,'Grenache','Grenache','Châteauneuf-du-Pape','Rood, krachtig','stil','rood'),
  D('rhone','Frankrijk','Domaine de la Colline','Domaine de la Colline',2021,'Syrah','Syrah','Crozes-Hermitage','Rood, peperig','stil','rood'),
  D('rhone','Frankrijk','Les Dentelles','Domaine Brunel',2020,'Grenache, Mourvèdre','Grenache','Gigondas','Rood, rijp','stil','rood'),
  D('loire','Frankrijk','Les Caillottes','Domaine Roux-Bellier',2023,'Sauvignon Blanc','Sauvignon Blanc','Sancerre','Wit, mineraal','stil','wit'),
  D('loire','Frankrijk','Château de la Ragotière','Château de la Ragotière',2023,'Melon de Bourgogne','Melon de Bourgogne','Muscadet Sèvre et Maine','Wit, zilt','stil','wit'),
  D('loire','Frankrijk','Clos Fumé','Domaine Desroches',2022,'Sauvignon Blanc','Sauvignon Blanc','Pouilly-Fumé','Wit, rokerig','stil','wit'),
  D('loire','Frankrijk','Les Coteaux','Domaine Huet-Marin',2022,'Chenin Blanc','Chenin Blanc','Vouvray','Wit, halfdroog','stil','wit'),
  D('loire','Frankrijk','La Bergerie','Domaine de la Bergerie',2021,'Cabernet Franc','Cabernet Franc','Chinon','Rood, fris','stil','rood'),
  D('loire','Frankrijk','Brut Ligérien','Caves de Saumur',2021,'Chenin Blanc','Chenin Blanc','Crémant de Loire','Mousserend, droog','mousserend','wit',['crémant']),
  D('toscane','Italië','Fattoria Il Leccio','Fattoria Il Leccio',2022,'Sangiovese','Sangiovese','Chianti','Rood, kersig','stil','rood'),
  D('toscane','Italië','Podere Le Querce','Podere Le Querce',2020,'Sangiovese','Sangiovese','Vino Nobile di Montepulciano','Rood, elegant','stil','rood'),
  D('toscane','Italië','Tenuta Mare Alto','Tenuta Mare Alto',2019,'Cabernet Sauvignon, Merlot','Cabernet Sauvignon','Bolgheri','Rood, vol','stil','rood'),
  D('rioja','Spanje','El Ciervo Joven','Bodegas El Ciervo',2023,'Tempranillo','Tempranillo','Rioja','Rood, fruitig','stil','rood',['joven','rioja alavesa']),
  D('nieuw-zeeland','Nieuw-Zeeland','Kererū Ridge','Kererū Ridge',2021,'Pinot Noir','Pinot Noir','Central Otago','Rood, zijdezacht','stil','rood'),
  D('nieuw-zeeland','Nieuw-Zeeland','Gannet Bay Syrah','Gannet Bay',2020,'Syrah','Syrah','Hawke\'s Bay','Rood, peperig','stil','rood'),
  D('champagne','Frankrijk','Brut Réserve','Maison Arlaux-Prévost',null,'Chardonnay, Pinot Noir, Meunier','','Champagne','Mousserend, droog','mousserend','wit',['brut']),
  D('champagne','Frankrijk','Blanc de Blancs','Champagne Delorme',null,'Chardonnay','Chardonnay','Champagne','Mousserend, fijn','mousserend','wit',['brut','blanc de blancs']),
  D('penedes','Spanje','Brut Nature','Caves Montserrat',null,'Xarel·lo, Macabeo, Parellada','','Cava','Mousserend, droog','mousserend','wit'),
  D('veneto','Italië','Extra Dry','Colli Trevigiani',null,'Glera','Glera','Prosecco','Mousserend, fruitig','mousserend','wit'),
  D('douro','Portugal','Quinta do Vale Escuro','Quinta do Vale Escuro',2020,'Touriga Nacional','Touriga Nacional','Douro','Rood, donker','stil','rood'),
  D('mosel','Duitsland','Steinbach Riesling','Weingut Steinbach',2022,'Riesling','Riesling','Mosel','Wit, fris','stil','wit'),
  D('pfalz','Duitsland','Spätburgunder Kalkstein','Weingut Hollerbach',2021,'Pinot Noir','Pinot Noir','Pfalz','Rood, licht','stil','rood'),
  D('nederland','Nederland','Heuvelrug Wit','Wijngaard De Heuvelrug',2023,'Solaris','Solaris','Utrechtse Heuvelrug','Wit, fris','stil','wit'),
  D('stellenbosch','Zuid-Afrika','Stellenbosch Oak Cabernet','Oak Valley Estate',2020,'Cabernet Sauvignon','Cabernet Sauvignon','Stellenbosch','Rood, stevig','stil','rood'),
  D('walker-bay','Zuid-Afrika','Walker Cove Chardonnay','Walker Cove',2022,'Chardonnay','Chardonnay','Hemel-en-Aarde','Wit, elegant','stil','wit'),
  D('stellenbosch','Zuid-Afrika','Kaapse Ster Brut','Kaapse Ster',null,'Chardonnay, Pinot Noir','','Cap Classique','Mousserend, droog','mousserend','wit'),
  D('maipo','Chili','Cordillera Cabernet','Viña Cordillera',2021,'Cabernet Sauvignon','Cabernet Sauvignon','Maipo','Rood, rond','stil','rood'),
  D('casablanca','Chili','Costa Fría','Viña Costa Fría',2023,'Sauvignon Blanc','Sauvignon Blanc','Casablanca','Wit, fris','stil','wit'),
  D('mendoza','Argentinië','Alto Andes Malbec','Bodega Alto Andes',2021,'Malbec','Malbec','Mendoza','Rood, vol','stil','rood'),
  D('californie','Verenigde Staten','Redwood Crest Chardonnay','Redwood Crest',2021,'Chardonnay','Chardonnay','Sonoma','Wit, romig','stil','wit'),
  D('californie','Verenigde Staten','Napa Bench Cabernet','Napa Bench Cellars',2019,'Cabernet Sauvignon','Cabernet Sauvignon','Napa Valley','Rood, krachtig','stil','rood'),
  D('barossa','Australië','Red Gum Shiraz','Red Gum Estate',2020,'Shiraz','Syrah','Barossa Valley','Rood, vol','stil','rood'),
  D('steiermark','Oostenrijk','Steirische Klassik','Weingut Pölzl',2022,'Sauvignon Blanc','Sauvignon Blanc','Südsteiermark','Wit, fris','stil','wit'),
  D('sussex','Verenigd Koninkrijk','Chalk Downs Brut','Chalk Downs',null,'Chardonnay, Pinot Noir','','Sussex','Mousserend, strak','mousserend','wit'),
  D('minho','Portugal','Loureiro','Quinta da Ribeira',2023,'Loureiro','Loureiro','Vinho Verde','Wit, licht parelend','stil','wit'),
  D('douro','Portugal','10 Year Old Tawny','Casa do Rio',null,'Touriga Nacional, Tinta Roriz','','Porto','Versterkt, zoet','versterkt','rood'),
  D('rheinhessen','Duitsland','Silvaner Trocken','Weingut Kellermann',2022,'Silvaner','Silvaner','Rheinhessen','Wit, droog','stil','wit'),
  D('weinviertel','Oostenrijk','Grüner Veltliner','Weingut Hofbauer',2023,'Grüner Veltliner','Grüner Veltliner','Weinviertel','Wit, peperig','stil','wit'),
  D('western-cape','Zuid-Afrika','Old Vine Chenin','Swartberg Cellars',2022,'Chenin Blanc','Chenin Blanc','Swartland','Wit, rijk','stil','wit'),
  D('colchagua','Chili','Carmenère Reserva','Viña Los Robles',2021,'Carmenère','Carmenère','Colchagua','Rood, kruidig','stil','rood'),
  D('mclaren','Australië','Grenache Old Vine','Seaview Hill',2021,'Grenache','Grenache','McLaren Vale','Rood, sappig','stil','rood'),
  D('elzas','Frankrijk','Riesling Réserve','Domaine Kientzler-Haas',2022,'Riesling','Riesling','Alsace','Wit, droog','stil','wit'),
  D('elzas','Frankrijk','Gewurztraminer','Cave de Ribeauvillé-Sud',2022,'Gewurztraminer','Gewurztraminer','Alsace','Wit, aromatisch','stil','wit'),
  D('elzas','Frankrijk','Crémant d\'Alsace Brut','Maison Wolfberger-Est',null,'Pinot Blanc','Pinot Blanc','Crémant d\'Alsace','Mousserend, fris','mousserend','wit',['crémant']),
  D('languedoc','Frankrijk','Les Garrigues','Domaine du Mas Rouge',2022,'Syrah, Grenache','Syrah','Pays d\'Oc','Rood, kruidig','stil','rood'),
  D('languedoc','Frankrijk','Picpoul Côté Mer','Cave de l\'Étang',2023,'Piquepoul','Piquepoul','Picpoul de Pinet','Wit, zilt','stil','wit'),
  D('languedoc','Frankrijk','Château Fontcalme','Château Fontcalme',2021,'Carignan, Syrah','Carignan','Corbières','Rood, warm','stil','rood'),
  D('provence','Frankrijk','Rosé de la Plage','Domaine des Pins Bleus',2023,'Grenache, Cinsault','Grenache','Côtes de Provence','Rosé, licht','stil','rosé'),
  D('provence','Frankrijk','Bandol Rouge','Domaine de la Calanque',2019,'Mourvèdre','Mourvèdre','Bandol','Rood, krachtig','stil','rood'),
  D('zuidwest','Frankrijk','Malbec Noir','Château Lagrézette-Bas',2020,'Malbec','Malbec','Cahors','Rood, donker','stil','rood'),
  D('zuidwest','Frankrijk','Colombard-Ugni','Domaine du Tariquet-Haut',2023,'Colombard, Ugni Blanc','Colombard','Côtes de Gascogne','Wit, fris','stil','wit'),
  D('piemonte','Italië','Barbera Superiore','Cascina Bricco',2021,'Barbera','Barbera','Barbera d\'Asti','Rood, sappig','stil','rood'),
  D('piemonte','Italië','Barolo Classico','Cantina del Colle',2018,'Nebbiolo','Nebbiolo','Barolo','Rood, tanninerijk','stil','rood'),
  D('piemonte','Italië','Gavi del Comune','Tenuta La Pieve',2023,'Cortese','Cortese','Gavi','Wit, fris','stil','wit'),
  D('veneto','Italië','Ripasso Classico','Corte dei Ciliegi',2020,'Corvina, Rondinella','Corvina','Valpolicella Ripasso','Rood, rond','stil','rood'),
  D('veneto','Italië','Amarone Classico','Villa Sanmarco',2017,'Corvina, Rondinella','Corvina','Amarone della Valpolicella','Rood, vol','stil','rood'),
  D('veneto','Italië','Soave Classico','Cantina del Monte',2023,'Garganega','Garganega','Soave','Wit, zacht','stil','wit'),
  D('puglia','Italië','Primitivo Vecchie Vigne','Masseria Sole',2021,'Primitivo','Primitivo','Primitivo di Manduria','Rood, vol','stil','rood'),
  D('abruzzo','Italië','Montepulciano','Cantina Gran Sasso-Est',2022,'Montepulciano','Montepulciano','Montepulciano d\'Abruzzo','Rood, soepel','stil','rood'),
  D('sicilie','Italië','Nero d\'Avola','Baglio delle Palme',2022,'Nero d\'Avola','Nero d\'Avola','Terre Siciliane','Rood, fruitig','stil','rood'),
  D('sicilie','Italië','Etna Rosso','Tenuta Lavica',2020,'Nerello Mascalese','Nerello Mascalese','Etna Rosso','Rood, elegant','stil','rood'),
  D('ribera','Spanje','Crianza','Bodegas Peñalta',2020,'Tempranillo','Tempranillo','Ribera del Duero','Rood, stevig','stil','rood',['crianza']),
  D('rueda','Spanje','Verdejo','Bodegas Los Pinos',2023,'Verdejo','Verdejo','Rueda','Wit, fris','stil','wit'),
  D('galicie','Spanje','Albariño','Adega Costa Verde',2023,'Albariño','Albariño','Rías Baixas','Wit, zilt','stil','wit'),
  D('priorat','Spanje','Llicorella','Celler Pedra Negra',2019,'Garnacha, Cariñena','Garnacha','Priorat','Rood, mineraal','stil','rood'),
  D('jumilla','Spanje','Monastrell','Bodegas Altiplano',2022,'Monastrell','Monastrell','Jumilla','Rood, rijp','stil','rood'),
  D('la-mancha','Spanje','Airén Joven','Viñas de la Llanura',2023,'Airén','Airén','La Mancha','Wit, licht','stil','wit'),
  D('santorini','Griekenland','Assyrtiko','Estate Kaldera',2022,'Assyrtiko','Assyrtiko','Santorini','Wit, mineraal','stil','wit'),
  D('tokaj','Hongarije','Tokaji Aszú 5 Puttonyos','Dobogó-Kert',2017,'Furmint','Furmint','Tokaj','Wit, zoet','zoet','wit'),
  D('kakheti','Georgië','Saperavi','Qvevri Cellar Alazani',2021,'Saperavi','Saperavi','Kakheti','Rood, donker','stil','rood'),
  D('canelones','Uruguay','Tannat Reserva','Bodega Río Claro',2020,'Tannat','Tannat','Canelones','Rood, stevig','stil','rood'),
  D('belgie','België','Chardonnay Hageland','Wijndomein Kluisberg',2022,'Chardonnay','Chardonnay','Hageland','Wit, fris','stil','wit'),
  D('niagara','Canada','Vidal Icewine','Frost Ridge',2019,'Vidal','Vidal','Niagara Peninsula','Wit, zoet','zoet','wit'),
  /* echte Icons */
  D('nieuw-zeeland','Nieuw-Zeeland','Cloudy Bay Sauvignon Blanc','Cloudy Bay',2023,'Sauvignon Blanc','Sauvignon Blanc','Marlborough','Wit, uitbundig','stil','wit',[],true),
  D('toscane','Italië','Tignanello','Marchesi Antinori',2020,'Sangiovese, Cabernet Sauvignon','Sangiovese','Toscana IGT','Rood, vol','stil','rood',[],true),
  D('champagne','Frankrijk','Dom Pérignon','Moët & Chandon',2013,'Chardonnay, Pinot Noir','','Champagne','Mousserend, verfijnd','mousserend','wit',['millésime','prestige'],true),
  D('champagne','Frankrijk','Krug Grande Cuvée','Krug',null,'Pinot Noir, Chardonnay, Meunier','','Champagne','Mousserend, rijk','mousserend','wit',['prestige'],true),
  D('toscane','Italië','Sassicaia','Tenuta San Guido',2019,'Cabernet Sauvignon, Cabernet Franc','Cabernet Sauvignon','Bolgheri Sassicaia','Rood, elegant','stil','rood',[],true),
  D('ribera','Spanje','Vega Sicilia Único','Vega Sicilia',2012,'Tempranillo, Cabernet Sauvignon','Tempranillo','Ribera del Duero','Rood, complex','stil','rood',[],true),
  D('bordeaux','Frankrijk','Château d\'Yquem','Château d\'Yquem',2015,'Sémillon, Sauvignon Blanc','Sémillon','Sauternes','Wit, zoet','zoet','wit',[],true),
  D('barossa','Australië','Penfolds Grange','Penfolds',2018,'Shiraz','Syrah','South Australia','Rood, krachtig','stil','rood',[],true),
  D('californie','Verenigde Staten','Opus One','Opus One',2019,'Cabernet Sauvignon, Merlot','Cabernet Sauvignon','Napa Valley','Rood, vol','stil','rood',[],true),
  D('bordeaux','Frankrijk','Château Margaux','Château Margaux',2015,'Cabernet Sauvignon, Merlot','Cabernet Sauvignon','Margaux','Rood, verfijnd','stil','rood',[],true),
  D('bordeaux','Frankrijk','Pétrus','Pétrus',2016,'Merlot','Merlot','Pomerol','Rood, fluweelzacht','stil','rood',[],true),
  D('bourgogne','Frankrijk','Romanée-Conti','Domaine de la Romanée-Conti',2018,'Pinot Noir','Pinot Noir','Romanée-Conti Grand Cru','Rood, legendarisch','stil','rood',[],true)
];

if (typeof module !== 'undefined') module.exports = {LANDS, AREAS, LANDPAL, SETS, POOL};
